// lib/data/services/order_service.dart

import 'dart:io';
import 'dart:typed_data';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'dart:developer' as developer;

import '../models/order_model.dart';
import '../models/notification_model.dart';
import '../../domain/repositories/order_repository.dart';
import '../../domain/repositories/shop_repository.dart';
import '../../domain/repositories/notification_repository.dart';
import '../../domain/repositories/storage_service.dart';
import '../repositories/order_repository_impl.dart';
import '../repositories/shop_repository_impl.dart';
import '../repositories/notification_repository_impl.dart';
import '../repositories/storage_service_impl.dart';
import 'price_calculator_service.dart';

/// Input data structure for submitting items within an order
class OrderItemInput {
  final String serviceId;
  final String fileName;
  final int pages;
  final int copies;
  final String colorMode; // 'bw' | 'color'
  final String paperSize; // 'A4' | 'A3' | 'F4'
  final String? finishing;
  final bool isDoubleSided;
  final File? file;
  final Uint8List? bytes;

  OrderItemInput({
    required this.serviceId,
    required this.fileName,
    required this.pages,
    required this.copies,
    required this.colorMode,
    required this.paperSize,
    this.finishing,
    required this.isDoubleSided,
    this.file,
    this.bytes,
  });
}

class OrderService {
  final OrderRepository _orderRepository;
  final ShopRepository _shopRepository;
  final NotificationRepository _notificationRepository;
  final StorageService _storageService;
  final PriceCalculatorService _priceCalculatorService;

  OrderService({
    required OrderRepository orderRepository,
    required ShopRepository shopRepository,
    required NotificationRepository notificationRepository,
    required StorageService storageService,
    required PriceCalculatorService priceCalculatorService,
  })  : _orderRepository = orderRepository,
        _shopRepository = shopRepository,
        _notificationRepository = notificationRepository,
        _storageService = storageService,
        _priceCalculatorService = priceCalculatorService;

  /// Submit order flow:
  /// 1. Upload files to Storage
  /// 2. Fetch base prices & calculate subtotal and total prices via PriceCalculatorService
  /// 3. Save order and order items to database
  /// 4. Generate notification for the shop owner
  /// 5. Return order ID
  Future<String> submitOrder({
    required String userId,
    required String shopId,
    required String deliveryType, // 'pickup' | 'delivery'
    String? addressId,
    required String paymentMethod,
    String? note,
    required List<OrderItemInput> inputs,
    double deliveryFee = 10000.0,
  }) async {
    if (inputs.isEmpty) {
      throw ArgumentError('Order must contain at least one item');
    }

    // 1. Fetch shop services to look up active base prices
    final services = await _shopRepository.getShopServices(shopId);
    final serviceMap = {for (var s in services) s.id: s};

    final List<OrderItemModel> itemsToInsert = [];

    // 2. Process and upload each item
    for (final input in inputs) {
      final service = serviceMap[input.serviceId];
      if (service == null) {
        throw Exception('Service with ID ${input.serviceId} is not available at this shop');
      }

      // Upload file to Supabase Storage
      final fileUrl = await _storageService.uploadOrderFile(
        userId: userId,
        fileName: input.fileName,
        file: input.file,
        bytes: input.bytes,
      );

      // Calculate the subtotal price locally
      final isColor = input.colorMode.toLowerCase() == 'color';
      final itemBreakdown = _priceCalculatorService.calculateItemPrice(
        basePrice: service.basePrice,
        pages: input.pages,
        copies: input.copies,
        isColor: isColor,
        finishing: input.finishing,
        isDoubleSided: input.isDoubleSided,
      );

      // Create OrderItemModel
      final itemModel = OrderItemModel(
        id: '', // Will be generated by DB
        orderId: '', // Will be set during insertion
        serviceId: input.serviceId,
        fileUrl: fileUrl,
        fileName: input.fileName,
        pages: input.pages,
        copies: input.copies,
        colorMode: input.colorMode,
        paperSize: input.paperSize,
        finishing: input.finishing,
        isDoubleSided: input.isDoubleSided,
        subtotal: itemBreakdown.subtotal,
      );

      itemsToInsert.add(itemModel);
    }

    // 3. Calculate order total price
    final orderBreakdown = _priceCalculatorService.calculateOrderPrice(
      items: itemsToInsert,
      deliveryType: deliveryType,
      deliveryFee: deliveryFee,
    );

    // 4. Create OrderModel
    final orderModel = OrderModel(
      id: '', // Generated by DB
      userId: userId,
      shopId: shopId,
      status: 'pending',
      deliveryType: deliveryType,
      addressId: addressId,
      totalPrice: orderBreakdown.totalPrice,
      paymentMethod: paymentMethod,
      paymentProofUrl: null,
      paymentStatus: 'pending',
      note: note,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    );

    // 5. Save order and order items in database
    final orderId = await _orderRepository.createOrder(orderModel, itemsToInsert);

    // 6. Notify shop owner
    try {
      final shop = await _shopRepository.getShopById(shopId);
      final notification = NotificationModel(
        id: '', // Generated by DB
        userId: shop.ownerId,
        title: 'Pesanan Baru Masuk',
        body: 'Anda menerima pesanan baru dengan total Rp ${orderBreakdown.totalPrice.toStringAsFixed(0)}.',
        type: 'order_new',
        isRead: false,
        createdAt: DateTime.now(),
      );
      await _notificationRepository.createNotification(notification);
    } catch (e) {
      // Log notification error but don't fail order submission
      developer.log('Warning: Failed to send notification to shop owner: $e');
    }

    return orderId;
  }
}

/// Riverpod provider for OrderService
final orderServiceProvider = Provider<OrderService>((ref) {
  return OrderService(
    orderRepository: ref.watch(orderRepositoryProvider),
    shopRepository: ref.watch(shopRepositoryProvider),
    notificationRepository: ref.watch(notificationRepositoryProvider),
    storageService: ref.watch(storageServiceProvider),
    priceCalculatorService: ref.watch(priceCalculatorServiceProvider),
  );
});
